project_name: qodana
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
nfpms:
  - vendor: "JetBrains s.r.o."
    homepage: "https://github.com/JetBrains/qodana-cli"
    maintainer: "Qodana <qodana-support@jetbrains.com>"
    description: "🔧 Run Qodana as fast as possible, with minimum effort required"
    license: "Apache-2.0"
    formats:
      - apk
      - deb
      - rpm
brews:
  - tap:
      owner: JetBrains
      name: homebrew-utils
    commit_author:
      name: "tiulpin"
      email: "viktor@tiulp.in"
    commit_msg_template: ":sparkles: Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/JetBrains/qodana-cli"
    description: "🔧 Run Qodana as fast as possible, with minimum effort required"
    license: "Apache-2.0"
scoop:
  bucket:
    owner: JetBrains
    name: scoop-utils
  commit_author:
    name: "tiulpin"
    email: "viktor@tiulp.in"
  commit_msg_template: ":sparkles: Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  folder: Scoops
  homepage: "https://github.com/JetBrains/qodana-cli"
  description: "🔧 Run Qodana as fast as possible, with minimum effort required"
  license: "Apache-2.0"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  footer: |
    ## Install
    
    #### macOS and Linux
    ##### Install with [Homebrew](https://brew.sh) (recommended)
    ```console
    brew tap jetbrains/utils
    brew install qodana
    ```
    ##### Install with our installer
    ```console
    curl -fsSL https://jb.gg/qodana-cli/install | bash
    ```
    
    #### Windows
    ##### Install with [Scoop](https://scoop.sh) (recommended)
    ```console
    scoop bucket add https://github.com/JetBrains/scoop-utils
    scoop install qodana
    ```
    ##### Install with our installer
    ```powershell
    iwr https://jb.gg/qodana-cli/install.ps1 -useb | iex
    ```
    
    #### Anywhere else
    #### Install with [Go](https://go.dev/doc/install)
    ```console
    go install github.com/JetBrains/qodana-cli@latest
    ```
    Alternatively, you can install the latest binary (or the apt/rpm/deb package) from this page.
    
    ## Update
    Update to the latest version depends on how you choose to install `qodana` on your machine.
    #### Update on Linux and macOS
    ```shell
    curl -fsSL https://jb.gg/qodana-cli/install | bash
    ```
    #### Update on Windows
    ```powershell
    iwr https://jb.gg/qodana-cli/install.ps1 -useb | iex
    ```
    #### Update with [Homebrew](https://brew.sh)
    ```shell
    brew upgrade qodana
    ```
    #### Update with [Scoop](https://scoop.sh)
    ```shell
    scoop update qodana
    ```
    #### Update with [Go](https://go.dev/doc/install)
    ```shell
    go install github.com/JetBrains/qodana-cli@latest
    ```
changelog:
  sort: asc
  filters:
    exclude:
      - '^:memo:'
      - '^:bricks:'
      - '^:recycle:'
