#!/bin/sh
#
# Copyright 2021-2025 JetBrains s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MESSAGE="This Qodana image is non-privileged and does not support sudo, please use the jetbrains/qodana-$QD_IMAGE:$QD_VERSION-privileged image if you need elevated privileges"

if [ -n "$TEAMCITY_VERSION" ]; then
    # TeamCity
    echo "##teamcity[buildProblem description='${MESSAGE}']"

elif [ -n "$JENKINS_URL" ]; then
    # Jenkins
    echo "[JENKINS_ERROR] ${MESSAGE}"

elif [ "${GITHUB_ACTIONS}" = "true" ]; then
    # GitHub Actions
    echo "::error file=sudo.sh,line=1::${MESSAGE}"

elif [ -n "$TF_BUILD" ]; then
    # Azure Pipelines
    echo "##vso[task.logissue type=error;sourcepath=sudo.sh;linenumber=1;columnnumber=1;code=NonPrivilegedSudo;]${MESSAGE}"

else
    # CircleCI, Bitbucket, GitLab, local, or any unknown environment
    echo "ERROR: ${MESSAGE}"
fi

exit 1
