name: Mock Dependencies
description: |
  Create empty placeholder files for embedded dependencies that are not available in the public repository.
  These files are required for Go compilation and linting to succeed.

runs:
  using: composite
  steps:
    - name: Create mock artifact dependencies
      shell: bash
      # Note: these dependencies contain closed-source code and are not currently available on Github.
      run: >-
        touch
        cdnet/clt.zip
        cdnet/clt.sha256.bin
        cdnet/clt.path.txt
        internal/tooling/intellij-report-converter.jar
        clang/clang-tidy-linux-amd64.tar.gz
        clang/clang-tidy-linux-amd64.tar.gz.sha256.bin
        clang/clang-tidy-linux-arm64.tar.gz
        clang/clang-tidy-linux-arm64.tar.gz.sha256.bin
        clang/clang-tidy-windows-amd64.zip
        clang/clang-tidy-windows-amd64.zip.sha256.bin
        clang/clang-tidy-windows-arm64.zip
        clang/clang-tidy-windows-arm64.zip.sha256.bin
        clang/clang-tidy-darwin-amd64.tar.gz
        clang/clang-tidy-darwin-amd64.tar.gz.sha256.bin
        clang/clang-tidy-darwin-arm64.tar.gz
        clang/clang-tidy-darwin-arm64.tar.gz.sha256.bin
