version: 2
project_name: qodana-cdnet
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }} -X main.buildDateStr={{ .Date }}
    hooks:
      post:
        - sh -c "set -e; if [ '{{ .Env.SIGN }}' = 'true' -a '{{ .Os }}' = 'windows' -a '{{ .Arch }}' = 'amd64' ]; then codesign -signed-files-dir ./dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v1/ './dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v1/qodana-cdnet.exe' ; fi"
        - sh -c "set -e; if [ '{{ .Env.SIGN }}' = 'true' -a '{{ .Os }}' = 'windows' -a '{{ .Arch }}' = 'arm64' ]; then codesign -signed-files-dir ./dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v8.0/ './dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/qodana-cdnet.exe' ; fi"
        - sh -c "set -e; if [ '{{ .Env.SIGN }}' = 'true' -a '{{ .Os }}' = 'darwin' -a '{{ .Arch }}' = 'amd64' ]; then codesign -denoted-content-type=application/x-mac-app-bin -signed-files-dir ./dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v1/ './dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v1/qodana-cdnet' ; fi"
        - sh -c "set -e; if [ '{{ .Env.SIGN }}' = 'true' -a '{{ .Os }}' = 'darwin' -a '{{ .Arch }}' = 'arm64' ]; then codesign -denoted-content-type=application/x-mac-app-bin -signed-files-dir ./dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v8.0/ './dist/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}/qodana-cdnet' ; fi"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
archives:
  -
    formats: [ 'binary' ]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"