version: 2
project_name: qodana-cdnet
builds:
  - env:
      - CGO_ENABLED=0
      - TARGETOS={{.Os}}
      - TARGETARCH={{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }} -X main.buildDateStr={{ .Date }}
    hooks:
      pre:
        - cmd: | # Run 'go generate'
            go run ../scripts/generate-recursive.go
      post:
        - cmd: go run ../scripts/sign.go {{ .ProjectName }}
snapshot:
  version_template: "{{ incpatch .Version }}-next"
archives:
  -
    formats: [ 'binary' ]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
git:
  ignore_tags:
    - nightly