name: Setup Docker
description: Install Docker engine.
inputs:
  version:
    required: true
    default: latest
    description: Either "latest", or "[v]major[.minor[.patch]]" version of the engine.
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      run: pip install natsort htmllistparse

    - name: Normalize version
      uses: mathiasvr/command-output@v2.0.0
      id: normalize-version
      env:
        QUERY: ${{ inputs.version }}
      with:
        shell: python
        run: | # python
          import json
          import platform
          import re
          import sys
          import os
          from urllib.request import urlopen

          import htmllistparse
          from natsort import natsorted


          def fail(message):
              print(message, file=sys.stderr)
              sys.exit(1)


          def latest_binary(version, os=None, arch=None):
              """For a given X or X.Y version, find the latest X.Y.Z released binary."""
              def host_os():
                  RENAME = {
                      "Darwin": "mac",
                      "Linux": "linux",
                      "Windows": "win",
                  }

                  return RENAME[platform.system()]


              def host_arch():
                  RENAME = {
                      "AMD64": "x86_64",
                      "x86_64": "x86_64",
                      "arm64": "aarch64",
                  }

                  return RENAME[platform.machine()]

              os = os or host_os()
              arch = arch or host_arch()

              re_target_binary_name = re.compile(fr"docker-({re.escape(version)}(?:\.\d+)*)")

              _, binary_releases = htmllistparse.fetch_listing(f"https://download.docker.com/{os}/static/stable/{arch}/")
              matching_versions = []
              for binary_release in binary_releases:
                  filename = binary_release.name
                  if m := re_target_binary_name.match(filename):
                      matching_versions.append(m[1])

              matching_versions = natsorted(matching_versions)
              if len(matching_versions) == 0:
                  fail(f"No binary release found for version '{version}'")
              return matching_versions[-1]


          query = os.getenv("QUERY") or sys.argv[1]
          if query == "latest":
              print(query)
          elif m := re.fullmatch(r"v?(\d+\.\d+\.\d+)", query):  # Full version specified
              print(f"v{m[1]}")
          elif m := re.fullmatch(r"v?(\d+(?:\.\d+)?)", query):  # One or two semver components omitted
              print("v", latest_binary(m[1]), sep="")
          else:
              fail(f"Cannot normalize version '{query}'")

    - if: runner.os == 'macOS'
      name: Install compatible version of QEMU for macOS
      # Workaround for QEMU failures when starting Docker via Lima on a GitHub-hosted runner.
      # I found no issue for this, but this is the same workaround used in https://github.com/lima-vm/lima.
      shell: bash
      run: | # shell
        set -euxo pipefail

        brew-install() {
          # Install a specific package version from Homebrew.
          #
          # This script was adapted from https://github.com/lima-vm/lima/blob/master/hack/brew-install-version.sh,
          # licensed from the Lima authors under Apache-2.0.
          FORMULA="$1"
          VERSION="$2"

          TEMP_DIR=$(mktemp -d "brew-install")
          trap "rm -rf $TEMP_DIR" RETURN

          HOMEBREW_DIR="$TEMP_DIR/homebrew-core"
          git clone --filter=tree:0 https://github.com/Homebrew/homebrew-core "$HOMEBREW_DIR"

          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_INSTALL_UPGRADE=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1

          TAP=lima/tap
          if ! brew tap | grep -q "^${TAP}\$"; then
            brew tap-new "$TAP"
          fi

          # Get the latest commit id for the commit that updated this bottle
          SHA=$(git -C "$HOMEBREW_DIR" log --max-count 1 --grep "^${FORMULA}: update ${VERSION} bottle" --format="%H")
          if [[ -z $SHA ]]; then
            echo "${FORMULA} ${VERSION} not found"
            exit 1
          fi

          OUTPUT="$(brew --repo "$TAP")/Formula/${FORMULA}.rb"
          RAW="https://raw.githubusercontent.com/Homebrew/homebrew-core"
          curl -s "${RAW}/${SHA}/Formula/${FORMULA::1}/${FORMULA}.rb" -o "$OUTPUT"

          if brew ls -1 | grep -q "^${FORMULA}\$"; then
            brew uninstall "$FORMULA" --ignore-dependencies
          fi
          brew install "${TAP}/${FORMULA}"
        }

        brew-install qemu 10.1.1

    - uses: docker/setup-docker-action@v4
      with:
        version: ${{ steps.normalize-version.outputs.stdout }}

    - name: Docker version
      shell: bash
      run: docker version --format '{{.Server.Version}}'