name: 'post-release'
on:
  release:
    types: [released]
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event.release.name != 'nightly'
        with:
          repository: 'jetbrains/qodana-action'
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Upgrade and send PR
        if: github.event.release.name != 'nightly'
        run: |
          cd common && node update-cli.js && cd ..
          npm ci
          npm run build && npm run -w scan package && npm run -w vsts package
          git config user.name qodana-bot
          git config user.email qodana-support@jetbrains.com
          git checkout -b next
          git add .
          git commit -m ":arrow_up: Update \`qodana\` to \`${{ github.event.release.name }}\`"
          git push origin next --force
          gh pr create --repo jetbrains/qodana-action --base main --head next --title ":arrow_up: Update \`qodana\` to the \`${{ github.event.release.name }}\`" --body "This automated PR updates \`qodana\` to the latest version. Please review and merge it if everything is fine."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  winget:
    runs-on: ubuntu-latest
    if: github.event.release.name != 'nightly'
    steps:
      - run: >
          set -e &&
          echo "${SHA256} *komac.tar.gz" > shasum &&
          curl -fSsL https://github.com/russellbanks/Komac/releases/download/v2.2.1/KomacPortable-linux-x64.tar.gz -o komac.tar.gz &&
          sha256sum --check --status shasum
          tar -xzf komac.tar.gz && chmod +x KomacPortable-linux-x64
        env:
          SHA256: 4d0530246a7e867166bc728c4128832765c24dc6ca197cbad99dc983fabd2f81
      - run: |
          export VERSION=${{ github.event.release.name }}
          ./KomacPortable-linux-x64 update \
            --id 'JetBrains.QodanaCLI' \
            --version $(echo "$VERSION" | sed 's/^v//') \
            --urls "https://github.com/JetBrains/qodana-cli/releases/download/$VERSION/qodana_windows_arm64.zip,https://github.com/JetBrains/qodana-cli/releases/download/$VERSION/qodana_windows_x86_64.zip" \
            --submit
        env:
          GITHUB_TOKEN: ${{ secrets.WINGET_GH_PAT_TOKEN }}
